# scripts/devbox/api.yml
services:
  arch-dev-api:
    image: python:3.11-slim
    container_name: arch-dev-api
    restart: unless-stopped
    volumes:
      - /opt/compute-infra:/opt/compute-infra
      - /var/lib/libvirt/images:/var/lib/libvirt/images
    command: >
      sh -c "pip install flask && python /opt/compute-infra/api/api.py"
    privileged: true
    networks:
      - devnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${API_FQDN}`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=le"
      - "traefik.http.services.api.loadbalancer.server.port=5000"

networks:
  devnet:
    external: true