version: "3.8"

services:
  arch-vnc:
    image: localhost:5000/omarchy-vnc:latest
    container_name: arch-vnc-template
    restart: unless-stopped
    ports:
      - "6080:6080"
    environment:
      - VNC_PASSWD=omarchy
      - RESOLUTION=1920x1080
    volumes:
      - /dev/shm:/dev/shm
      - arch_home:/home/omarchy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.arch.rule=Host(`arch.yourdomain.com`)"
      - "traefik.http.routers.arch.entrypoints=websecure"
      - "traefik.http.routers.arch.tls.certresolver=le"
      - "traefik.http.services.arch.loadbalancer.server.port=6080"
    networks:
      - devnet

networks:
  devnet:
    external: true

volumes:
  arch_home:
