version: "3.8"

services:
  db:
    image: mariadb:10.6
    container_name: nextcloud-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloudpass123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - devnet

  nextcloud:
    image: nextcloud:apache
    container_name: nextcloud
    restart: always
    depends_on: [db]
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      MYSQL_PASSWORD: nextcloudpass123
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`files.yourdomain.com`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=le"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
    networks:
      - devnet

networks:
  devnet:
    external: true

volumes:
  db_data:
  nextcloud_data:
